name: Publish Release YAML

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install X11 and Wayland dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            xorg-dev \
            libxtst-dev \
            libpng++-dev \
            xcb \
            libxcb-xkb-dev \
            x11-xkb-utils \
            libx11-xcb-dev \
            libxkbcommon-x11-dev \
            libxkbcommon-dev \
            libwayland-dev \
            wayland-protocols \
            libxkbcommon-dev

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
